"""Audit action constants (SR-023)."""


class AuditAction:
    AUTH_LOGIN = "AUTH_LOGIN"
    AUTH_LOGOUT = "AUTH_LOGOUT"
    CLINICAL_ACCESS = "CLINICAL_ACCESS"
    CONSENT_GRANT = "CONSENT_GRANT"
    CONSENT_REVOKE = "CONSENT_REVOKE"
    ACCOUNT_CREATE = "ACCOUNT_CREATE"
    USER_TYPE_CHANGE = "USER_TYPE_CHANGE"
    GROUP_MODULE_CHANGE = "GROUP_MODULE_CHANGE"
    ATTACHMENT_ACCESS = "ATTACHMENT_ACCESS"
    APPOINTMENT_CREATE = "APPOINTMENT_CREATE"
    APPOINTMENT_STATE_CHANGE = "APPOINTMENT_STATE_CHANGE"
